# Generated by Django 4.2.9 on 2024-01-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.FloatField()),
                ('value2', models.FloatField()),
                ('result', models.FloatField()),
            ],
        ),
    ]
