# Generated by Django 4.2.9 on 2024-01-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translator',
            old_name='value1',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='translator',
            old_name='value2',
            new_name='y',
        ),
    ]
